In [1]:
# data analysis and wrangling
import pandas as pd
import numpy as np

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')

#settings
pd.options.display.max_columns = 250
pd.options.display.max_rows = 250
sns.set(style="whitegrid")

import warnings
warnings.simplefilter('ignore')

## Save Model

In [2]:
import pickle
from sklearn import tree
# save the classifier
def save_model(model, name):
    path = r'{0}.pkl'.format(name)
    with open(path, 'wb') as fid:
        pickle.dump(model, fid) 

## Calculate accuracy and confusion matrix

In [3]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

def calculate_accuracy_confusion_matrix(model, test_features, test_labels):
    # predicting for test values
    DT_test_pred = model.predict(test_features)
    clf_DT_accuracy = accuracy_score(test_labels, DT_test_pred, normalize = True)
    print(clf_DT_accuracy)

    # Confusion Metrices for Decision Tree on train data.
    from sklearn import metrics
    from sklearn.metrics import confusion_matrix
    print("Confusion Metrices for Decision Tree")
    print("{0}".format(metrics.confusion_matrix(test_labels, DT_test_pred, labels=[0, 1])))

    print("Classification Report")
    print("{0}".format(metrics.classification_report(test_labels, DT_test_pred, labels=[0, 1])))



## Preparing data 

In [4]:
# Load Data
df = pd.read_pickle("Brain_SelectedData.pkl")
df.head()

26      20      18      14      12    4263   4199    4192    4120  \
0  4380.0  3720.0  3674.0  1712.0  5889.0   785.0  433.0   105.0  5054.0   
1  3080.0  2153.0  3079.0   358.0  2616.0  2127.0    4.0   243.0  5171.0   
2  5546.0  1797.0  6354.0   987.0  6232.0  1531.0   76.0  2658.0  1229.0   
3  2006.0   752.0  4465.0   811.0  3725.0  1308.0    5.0     0.0  2542.0   
4  3686.0  2004.0  3557.0  1109.0  3994.0  2056.0  145.0  1045.0  2293.0   

    4052   3843    3842   3835   3489    3344    3145   3128    2986   2843  \
0    0.0    0.0  1025.0  991.0    0.0  1937.0  7545.0  256.0  6005.0  123.0   
1    0.0  245.0  1984.0  527.0    0.0  1646.0  5456.0  657.0  7469.0  479.0   
2  183.0  144.0  1268.0  716.0  310.0  3143.0  6608.0  358.0  8672.0    0.0   
3    0.0   13.0  1853.0  568.0    0.0  1670.0  5533.0  857.0  4789.0    0.0   
4    0.0   34.0  1406.0  640.0    0.0  2147.0  4889.0  345.0  5322.0    0.0   

     2790     2719    2717     2510    2497  1811    1743  1672    1663  1504  \
0  4013.0  11517.0   356.0  13373.0  6326.0  19.0  8048.0   7.0  1056.0   0.0   
1  2984.0  12044.0  1777.0  15696.0  2690.0  30.0  3704.0  31.0    35.0   0.0   
2  5388.0  16113.0  1556.0  17360.0  8406.0  45.0  3579.0   0.0     0.0   0.0   
3  2404.0  12614.0   641.0   7575.0  2883.0   0.0   259.0   0.0     0.0   0.0   
4  2490.0  10799.0   269.0  13924.0  4687.0   0.0  1178.0  19.0   112.0   0.0   

      860    712   442     371     292     271      237     236    224  \
0  3033.0   56.0   0.0  1846.0  1212.0  1336.0   7388.0  1206.0    0.0   
1  2080.0    3.0  83.0  1136.0   117.0    25.0   6579.0   108.0    0.0   
2  2988.0  112.0   0.0  2647.0  1189.0     1.0  11733.0  1937.0    0.0   
3  3022.0   50.0   0.0   542.0   516.0     1.0   3684.0   499.0  420.0   
4  2970.0   30.0   0.0   835.0   833.0     0.0   3418.0   882.0  195.0   

      222     175     163  162     160      61       2     4190  3977  3915  \
0   706.0  5990.0  1297.0  0.0  2760.0  2178.0  1778.0   7236.0  19.0   0.0   
1     0.0  2893.0  1048.0  0.0  1662.0  2229.0  1705.0   9966.0   8.0   1.0   
2  1939.0  7999.0  1911.0  0.0  1644.0  2629.0  2732.0  12414.0   0.0   0.0   
3  1353.0  4442.0  2020.0  0.0   680.0   519.0  1655.0   6370.0   0.0   0.0   
4   929.0  6486.0  2230.0  0.0  2610.0  2325.0  2334.0  10013.0   0.0   0.0   

     3909    3772    3769   3767    3697    3565    3416  3348    3276  \
0    27.0  8518.0  3582.0   44.0  5428.0  5409.0  2210.0   0.0  5752.0   
1   181.0  3089.0  4459.0  839.0  6953.0  3802.0  2946.0  28.0  6569.0   
2   811.0  7253.0  3323.0  843.0  2887.0  5145.0  3379.0  41.0  8359.0   
3    18.0  1434.0  1515.0  537.0  2106.0  4752.0  3726.0   0.0  6002.0   
4  1511.0  4493.0  2289.0  282.0  1797.0  3840.0  2053.0   4.0  3638.0   

     3207  3137   2999  2997  2939     2723     2722    2720   2714    2701  \
0   518.0  53.0  173.0  62.0   0.0  21442.0   6386.0   150.0    0.0   112.0   
1  1873.0  81.0    0.0  68.0   0.0  16045.0   6776.0  1274.0    0.0   323.0   
2     6.0   0.0    0.0   0.0   0.0  16959.0  12752.0  5977.0  185.0  2004.0   
3     4.0   0.0    1.0   0.0   0.0  14276.0   4852.0  3059.0    0.0  1573.0   
4     0.0   0.0    1.0   0.0   0.0  15418.0   6914.0  1699.0   25.0   397.0   

     2519    2512  2506   2504    2499   2307  2211    1952  1948    1928  \
0  3618.0  5115.0  77.0  244.0  3240.0  515.0   0.0  1917.0  15.0  4915.0   
1  1004.0  2841.0  39.0    1.0   975.0  133.0   0.0   862.0   0.0   831.0   
2  2053.0  9796.0  49.0  681.0  3160.0   18.0   2.0  2558.0  17.0  3131.0   
3  2059.0  1816.0  86.0    0.0   790.0   30.0   2.0   956.0   0.0  1000.0   
4  2336.0  4546.0  47.0  216.0  1051.0  321.0   0.0  1397.0   1.0  2551.0   

     1859    1855    1785    1781  1776  1706  1671  1657     1638  1516  \
0  3033.0  4285.0  1637.0  5957.0  42.0   0.0   0.0   0.0  12578.0   4.0   
1   977.0  2124.0   805.0  3542.0  37.0   0.0  14.0   6.0   9829.0   0.0   
2  1625.0  3638.0   886.0  6067.0  45.0   0.0   0.0   0.0

In [5]:
df2 = df.copy()

# target value
Y = df2.Sex.values
# features
X = df2.drop('Sex', axis = 1).values

In [6]:
from sklearn.model_selection import train_test_split
#Splitting the data.
split_test_size = 0.30

# Split the data into a training set and a test set
train_features, test_features, train_labels, test_labels = train_test_split(X, Y, test_size =  split_test_size, random_state = 42)

# Check whether the correct % data split (70/30 %)Train vs Test data.
print("{0:0.2f}% in training".format(  len(train_features)/len(df2.index) *100))
print("{0:0.2f}% in testing".format(  len(test_features)/len(df2.index) *100))


69.30% in training
30.70% in testing


## Training Model

### Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import accuracy_score

#train the model.
model = LogisticRegression(C=0.01, solver='liblinear')  #.fit(X_train,y_train)
model.fit(train_features, train_labels.ravel())

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
# performance on test set
calculate_accuracy_confusion_matrix(model, test_features, test_labels)

0.7428571428571429
Confusion Metrices for Decision Tree
[[11  3]
 [ 6 15]]
Classification Report
              precision    recall  f1-score   support

           0       0.65      0.79      0.71        14
           1       0.83      0.71      0.77        21

    accuracy                           0.74        35
   macro avg       0.74      0.75      0.74        35
weighted avg       0.76      0.74      0.75        35



In [9]:
# save the model
save_model(model, 'LR')

### Decision Boundary

In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score

#train the model.
model = DecisionTreeClassifier(max_depth=9, random_state = 42, criterion='gini') # entropy
model.fit(train_features, train_labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=9,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [11]:
# performace on test set
calculate_accuracy_confusion_matrix(model, test_features, test_labels)

0.5428571428571428
Confusion Metrices for Decision Tree
[[ 6  8]
 [ 8 13]]
Classification Report
              precision    recall  f1-score   support

           0       0.43      0.43      0.43        14
           1       0.62      0.62      0.62        21

    accuracy                           0.54        35
   macro avg       0.52      0.52      0.52        35
weighted avg       0.54      0.54      0.54        35



In [12]:
# save the model
save_model(model, 'DT')

### Random Forest

In [13]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(max_depth=8, n_estimators=25,min_samples_split=10, random_state=0)

model.fit(train_features, train_labels)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=8, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=10,
                       min_weight_fraction_leaf=0.0, n_estimators=25,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [14]:
# performance on test set
calculate_accuracy_confusion_matrix(model, test_features, test_labels)

0.7714285714285715
Confusion Metrices for Decision Tree
[[ 8  6]
 [ 2 19]]
Classification Report
              precision    recall  f1-score   support

           0       0.80      0.57      0.67        14
           1       0.76      0.90      0.83        21

    accuracy                           0.77        35
   macro avg       0.78      0.74      0.75        35
weighted avg       0.78      0.77      0.76        35



In [15]:
# save the model
save_model(model, 'RF')

### LightGBM

In [16]:
from lightgbm import LGBMClassifier

model=LGBMClassifier(n_estimators=300, learning_rate=0.01, num_leaves=80, max_depth = 9, colsample_bytree=0.2,
            reg_alpha=3, reg_lambda=1, min_split_gain=0.01, min_child_weight=40)

model.fit(train_features, train_labels.ravel())

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=0.2,
               importance_type='split', learning_rate=0.01, max_depth=9,
               min_child_samples=20, min_child_weight=40, min_split_gain=0.01,
               n_estimators=300, n_jobs=-1, num_leaves=80, objective=None,
               random_state=None, reg_alpha=3, reg_lambda=1, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [17]:
# performance of the model on test data
calculate_accuracy_confusion_matrix(model, test_features, test_labels)

0.6
Confusion Metrices for Decision Tree
[[ 0 14]
 [ 0 21]]
Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.60      1.00      0.75        21

    accuracy                           0.60        35
   macro avg       0.30      0.50      0.37        35
weighted avg       0.36      0.60      0.45        35



In [18]:
# save the model
save_model(model, 'LightGBM')

### XGBoost

In [19]:
import xgboost as xgb

model = xgb.XGBClassifier(booster="gbtree", max_depth=7, objective="binary:logistic", random_state=42, nthread=4, n_estimators = 20, eta = 0.05)

model.fit(train_features, train_labels.ravel())

ModuleNotFoundError: No module named 'xgboost'